---
- name: Wait for OpenSSH
  hosts: all
  gather_facts: false
  # vars:
  #   wait_for_ssh_port: 22              # SSH Port number to poll.
  #   wait_for_ssh_timeout_in_sec: 300   # Maximum number of seconds to wait for OpenSSH to become available.
  tasks:
    - name: Wait for OpenSSH
      ansible.builtin.wait_for:
        port: '{{ wait_for_ssh_port | default(22) }}'
        host: '{{ ( ansible_ssh_host | default(ansible_host) ) | default(inventory_hostname) }}'
        search_regex: OpenSSH
        delay: 10
        timeout: '{{ wait_for_ssh_timeout_in_sec | default(300) }}'
      vars:
        ansible_connection: local
...
