---
- name: Remove Bundle
  hosts: all
  environment:
    KUBECONFIG: "{{ openshift_kubeconfig_file }}"
  tasks: 

    - name: Remove Definitions
      with_items: "{{ bundle_packages }}"
      when: item.definition is defined and ( item.when | default(true) )
      kubernetes.core.k8s:
        state: absent
        definition: "{{ item.definition }}"

    - name: Remove Manifests
      with_items: "{{ bundle_packages }}"
      when: item.manifest_uri is defined and ( item.when | default(true) )
      kubernetes.core.k8s:
        state: absent
        src: "{{ item.manifest_uri }}"

    - name: Uninstall Helm Charts
      with_items: "{{ bundle_packages }}"
      when: item.chart_ref is defined and ( item.when | default(true) )
      kubernetes.core.helm:
        release_name: "{{ item.name | mandatory }}"
        release_namespace: "{{ item.namespace | default('default') }}"
        release_state: absent

    - name: Note
      debug:
        msg: "Note: Namespaces must be deleted manually!"
...
