---
- name: Wait for ArgoCD applications to be ready
  hosts: all
  tasks:
    - name: install required packaged
      ansible.builtin.apt:
        name:
         - jq
        update_cache: true
        state: present

    - name: wait for argoapplication status synced
      ansible.builtin.script: files/argo-application-sync.sh {{ openshift_kubeconfig_file }}
      changed_when: false
...
