---
- name: awx-iac
  hosts: localhost
  connection: local
  vars_files:
    # source the become passwort from an ansible vault
    - /path/to/awx-iac.vault
  vars:
    ansible_become_pass: '{{ ansible_become_pass }}'
    ssh_key_github: '{{ github_ssh_key }}'

  become: true
  roles:
    # this role will be merged into the playbook
    - role: /path/to/ansible-role-awx-iac
...
