---
roles:
  - name: gepaplexx.terraform
  - name: gepaplexx.csr_autoapprove
  - name: gepaplexx.dhcp
  - name: gepaplexx.dns
  - name: gepaplexx.haproxy
  - name: gepaplexx.infranodes
  - name: gepaplexx.k8stools
  - name: gepaplexx.longhorn
  - name: gepaplexx.microk8s
  - name: gepaplexx.nginx
  - name: gepaplexx.velero
  - name: gepaplexx.tftp
  - name: gepaplexx.unattended_upgrades
  - name: gepaplexx.cert_manager
  - name: gepaplexx.pxe
#  - name: gepaplexx.awx_iac
  - name: gepaplexx.kubeconfig_ca
...
